# Generated by Django 5.1 on 2025-12-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="temp_data",
            field=models.JSONField(default=dict),
        ),
    ]
