# Generated by Django 5.1 on 2025-12-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_usersession_temp_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("item_name", models.CharField(max_length=100)),
                ("qty", models.IntegerField()),
                ("price", models.IntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
