# Generated by Django 5.1 on 2025-12-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_webcart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebCart",
        ),
    ]
