# Generated by Django 5.1 on 2026-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_delete_webcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
